<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25512" started-at="2017-05-16T20:05:42Z" finished-at="2017-05-16T20:06:07Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25512" started-at="2017-05-16T20:05:42Z" finished-at="2017-05-16T20:06:07Z">
      <class name="qa.pageObject.TestCase.LoginTest">
        <test-method status="PASS" signature="doLogin(java.util.Hashtable)[pri:0, instance:qa.pageObject.TestCase.LoginTest@32ee6fee]" name="doLogin" duration-ms="24534" started-at="2017-05-17T01:35:42Z" data-provider="getData" finished-at="2017-05-17T01:36:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=singhrampal, ExpectedResult=Success, Password=*#ramface#, Runmode=Y, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="quit()[pri:0, instance:qa.pageObject.TestCase.LoginTest@32ee6fee]" name="quit" is-config="true" duration-ms="637" started-at="2017-05-17T01:36:06Z" finished-at="2017-05-17T01:36:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="SKIP" signature="doLogin(java.util.Hashtable)[pri:0, instance:qa.pageObject.TestCase.LoginTest@32ee6fee]" name="doLogin" duration-ms="2" started-at="2017-05-17T01:36:07Z" data-provider="getData" finished-at="2017-05-17T01:36:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=rampal.singh@sts.in, ExpectedResult=Success, Password=20synergy15, Runmode=N, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the Testcase as Runmode is : N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the Testcase as Runmode is : N
	at qa.pageObject.TestCase.LoginTest.doLogin(LoginTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="quit()[pri:0, instance:qa.pageObject.TestCase.LoginTest@32ee6fee]" name="quit" is-config="true" duration-ms="82" started-at="2017-05-17T01:36:07Z" finished-at="2017-05-17T01:36:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="SKIP" signature="doLogin(java.util.Hashtable)[pri:0, instance:qa.pageObject.TestCase.LoginTest@32ee6fee]" name="doLogin" duration-ms="2" started-at="2017-05-17T01:36:07Z" data-provider="getData" finished-at="2017-05-17T01:36:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=rampal.singh@sts.in, ExpectedResult=Unsuccessful, Password=xxxxxxx, Runmode=N, Browser=Mozilla}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the Testcase as Runmode is : N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the Testcase as Runmode is : N
	at qa.pageObject.TestCase.LoginTest.doLogin(LoginTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="quit()[pri:0, instance:qa.pageObject.TestCase.LoginTest@32ee6fee]" name="quit" is-config="true" duration-ms="49" started-at="2017-05-17T01:36:07Z" finished-at="2017-05-17T01:36:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- qa.pageObject.TestCase.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
